import { GridBox, Button, LineEdit, ListView, Switch, VerticalBox} from "std-widgets.slint";





export component AppWindow inherits Window {

    // callback calculate_num1(string);
    // callback calculate_num2(string);
    // callback calculate_sym(string);
    callback calc();

    in property <string> result: "";
    out property <string> num1ui: "";
    out property <string> num2ui: "";
    out property <string> symui: "";


//    function calculate(num1ui:string, num2ui:string, symui:string) {
//     //    calculate_num1(num1ui);
//     //    calculate_num2(num2ui);
//     //    calculate_sym(symui);
//     calc(num1ui, num2ui, symui);
//    } 

    background: #313e50;
    GridBox {
        padding:40px;
        spacing:20px;
        Row {
            VerticalBox {
                width: 300px;
                height: 60px;
                // for data in [
                //     { text: root.result , 
                //         color: #d7a91f, 
                //         bg: #1c232d, 
                //         font-weight: 600, 
                //         font-size: 50},
                // ] : Rectangle {
                //     x: 0;
                //     height: 30px;
                //     background: data.bg;
                //     width: parent.width;
                // }
                Rectangle {
                    x: 0;
                    height: 30px;
                    background: #1c232d;
                    width: parent.width;
                    Text {
                        text: root.result;
                        color: #d7a91f;
                        font-weight: 600; 
                    }
                }
                
            }
        }
        Row { 
            HorizontalLayout {
                alignment: space-between;

                Button { text: "𝜋 1"; primary: true; width: 140px; height: 40px; clicked => {num1ui.text = "𝜋"; root.num1ui="𝜋"}} 
                Button { text: "𝜋 2"; primary: true; width: 140px; height: 40px; clicked => {num2ui.text = "𝜋"; root.num2ui="𝜋"}}
            }
        }
        Row {
            num1ui := LineEdit {
                horizontal-alignment: center;
                font-size: 14px;
                width: 300px;
                height: 30px;
                placeholder-text: "Enter the first neumeral";
                edited => {root.num1ui = self.text}
            }
        }
        Row {            
            symui := LineEdit {
                horizontal-alignment: center;
                font-size: 14px;
                width: 300px;
                height: 30px;
                placeholder-text: "Enter a math symbol ( +, -, *, / )";
                edited => {root.symui = self.text}
            }
        }
        Row {
            num2ui := LineEdit {
                horizontal-alignment: center;
                font-size: 14px;
                width: 300px;
                height: 30px;
                placeholder-text: "Enter the second neumeral";
                edited => {root.num2ui = self.text}
            }
        }
        Row {
            Button { text: "Calculate"; clicked => {root.calc()} width: 300px;
            height: 30px;}
        }
    }
}





/*
in-out property <int> counter: 42;
callback request-increase-value();
VerticalBox { 
    Text {
        text: "Counter: \{root.counter}";
    }

    Button {
        text: "Increase value";
        clicked => {
            root.request-increase-value();
        }
    }
}
*/